# Site Settings
title:               Software Engineer's journey
tagline:             Konstantin Minevskiy
description:
baseurl:            ""
url:                ""
github:
  url:               ""
author:
  name:              "Konstantin Minevskiy"
  email:             "k@minevskiy.com"
  twitter:           "submell"
  github:            "kminevskiy"
  linkedin:          "kminevskiy"
navigation:
- title: About
  url: /about
- title: Articles
  url: /articles
- title: Contact
  url: /contact

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
